/// Flutter icons Github
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Github
///      fonts:
///       - asset: fonts/Github.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconDownloaded {
  IconDownloaded._();

  static const _kFontFam = 'IconDownloaded';
  static const String? _kFontPkg = null;

  static const IconData twitter =
      IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circled =
      IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad =
      IconData(0xf11b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow =
      IconData(0xf16c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData app_store =
      IconData(0xf36f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_play =
      IconData(0xf3ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain =
      IconData(0xf5dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git =
      IconData(0xf1d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
